### ISSUE TITLE
Gravity not working

### ISSUE THREAD

**Issue by caraujo777** [madelinegr/titanic_escape_room#2]
Code in master branch in titanicroom.unity

Gravity was defaulted to -9.8, which should be regular Earth gravity. However, even if it's set to a very low value such as -40, throwable items seem to be falling slowly. 

**Steps to reproduce:**
- Open unity titanicroom file in main branch
- Click on play
- Pick up items Pof Baroque or desklamp and then throw them on the floor
- Items fall slowly and do not follow Earth gravity

**Comment by EnriqueVega1995** [comment]
Gravity "feels" like is not working because a of an **scales** problem with objects in the scene.
The solution will be to re-scale all the objects outisde Unity (in a 3D editor like Blender), scale everything to a normal (human) size, and then place all objects in a new scene, replicating each object location. 

Here we compare a human character size that is about 1.8m with a Cube (1x1x1m) inside the huge scene.
![Scales](https://user-images.githubusercontent.com/44169869/67602741-88621480-f734-11e9-9eb3-98ce6d05a65e.png)

Character is so tiny that we almost can't see it when compared to the rest of the objects:
![Tiny](https://user-images.githubusercontent.com/44169869/67602746-8a2bd800-f734-11e9-8c74-67d877551713.png)

This is how physics should work  with normal size objects (in the backgorund we can see how lamp falls super slow because it's almost like a building size.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/44169869/67602752-8bf59b80-f734-11e9-9003-2c7bf829d519.gif)

**If there is not objection, we will proceed with the re-scale solution in another scene.**

**Comment by caraujo777** [comment]
This solution sounds good, please ping the slack channel if you are running into problems re-scaling any of the models! Thanks
